--Bai 4: phan 3: CSDL quan ly de an

Create Database QLDeAn
Use QLDeAn

CREATE TABLE NHANVIEN
	(
		MANV	VARCHAR(4)		NOT NULL,
		HONV	NVARCHAR(10)	NOT NULL,
		TENLOT	NVARCHAR(10)	NOT NULL,
		TENNV	NVARCHAR(10)	NOT NULL,
		NGSINH	DATE			NOT NULL,
		DCHI	NVARCHAR(40)	,
		PHAI	BIT				NOT NULL,
		MLUONG	MONEY			NOT NULL,
		MA_NQL	VARCHAR(4)		NOT NULL,
		PHONG	VARCHAR(4)	NOT NULL,
		CONSTRAINT PK_NHANVIEN	PRIMARY KEY (MANV)
	)
CREATE TABLE PHONGBAN
	(
		MAPHG	VARCHAR(4)		NOT NULL,
		TENPHG	NVARCHAR(20)	NOT NULL,
		TRGPHG	VARCHAR(4)		NOT NULL,
		NGNC	DATE			NOT NULL,
		CONSTRAINT PK_PHONGBAN	PRIMARY KEY (MAPHG),
		CONSTRAINT FK_PHONGBAN_NHANVIEN	FOREIGN KEY (TRGPHG)
		REFERENCES NHANVIEN(MANV)
		ON UPDATE CASCADE
		ON DELETE CASCADE
	)					
CREATE TABLE DIADIEMPHONG
	(
		MAPHG	VARCHAR(4)	NOT NULL,
		DIADIEM	NVARCHAR(20)	NOT NULL,
		CONSTRAINT PK_DIADIEMPHONG PRIMARY KEY (MAPHG, DIADIEM),
		CONSTRAINT FK_DIADIEMPHONG_PHONGBAN	FOREIGN KEY (MAPHG)
		REFERENCES PHONGBAN(MAPHG)
		ON UPDATE CASCADE
		ON DELETE CASCADE
	)
CREATE TABLE DEAN
	(
		MADA		VARCHAR(4)		NOT NULL,
		TENDA		NVARCHAR(20)	NOT NULL,
		DDIEM_DA	NVARCHAR(20)	NOT NULL,
		PHONG		NVARCHAR(20)	NOT NULL,
		NGBD_DA		DATE			NOT NULL,
		NGKT_DA		DATE			NOT NULL,
		CONSTRAINT PK_DEAN	PRIMARY KEY	(MADA)
	)
CREATE TABLE PHANCONG
	(
		MANV	VARCHAR(4)	NOT NULL,
		MADA	VARCHAR(4)	NOT NULL,
		THOIGIAN	DATETIME	NOT NULL,
		CONSTRAINT PK_PHANCONG PRIMARY KEY (MANV, MADA),
		CONSTRAINT FK_PHANCONG_NHANVIEN	FOREIGN KEY (MANV)
		REFERENCES NHANVIEN(MANV)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
		CONSTRAINT FK_DEAN_NHANVIEN	FOREIGN KEY (MADA)
		REFERENCES DEAN(MADA)
		ON UPDATE CASCADE
		ON DELETE CASCADE
	)
CREATE TABLE THANHNHAN
	(
		MANV	VARCHAR(4)	NOT NULL,
		MATN	VARCHAR(4)	NOT NULL,
		HOTN	NVARCHAR(10)	NOT NULL,
		TENTN	NVARCHAR(10)	NOT NULL,
		PHAI	BIT				NOT NULL,
		NGAYSINH	DATE		NOT NULL,
		QUANHE	NVARCHAR		NOT NULL,
		CONSTRAINT PK_THANHNHAN PRIMARY KEY (MANV, MATN),
		CONSTRAINT FK_THANHNHAN_NHANVIEN	FOREIGN KEY (MANV)
		REFERENCES NHANVIEN(MANV)
		ON UPDATE CASCADE
		ON DELETE CASCADE
	)

--Nhap du lieu

INSERT INTO NHANVIEN(MANV,HONV,TENLOT,TENNV,NGSINH,DCHI,PHAI,MLUONG,MA_NQL,PHONG) VALUES
	('NV01',N'Nguyễn',N'Chánh',N'Tín','2/20/1998',N'Tp HCM',1,2000000,'QL03','NC'),
	('NV02',N'Lê',N'Thanh',N'Tâm','5/26/1989',N'Vinh Long',0,3000000,'QL02','DH'),
	('NV03',N'Nguyễn',N'Thái',N'Thành','4/12/1999',N'Tp HCM',1,2500000,'QL01','NC'),
	('NV04',N'Đinh',N'Bá',N'Tiến','3/7/1996',N'Tp HCM',1,10000000,'QL02','DH')
INSERT INTO PHONGBAN(MAPHG,TENPHG,TRGPHG,NGNC) VALUES
	('P001', N'Hành chính','NV02','6/12/2000'),
	('P002', N'Nghiên cứu','NV04','6/6/2000'),
	('P003', N'Xây dựng','NV01','08/24/2001')
INSERT INTO DIADIEMPHONG(MAPHG,DIADIEM) VALUES
	('P001', N'Q11, Tp HCM'),
	('P002', N'Bình Thạnh, Tp HCM'),
	('P003',N'Thủ Dầu 1, Tp HCM')
INSERT INTO DEAN(MADA,TENDA,DDIEM_DA,PHONG,NGBD_DA,NGKT_DA) VALUES
	('DA01',N'Cầu Mỹ Thuận 2',N'Vĩnh Long',N'Xây dựng','12/12/2019','12/12/2022'),
	('DA02',N'Thi công QL908',N'Vĩnh long',N'Thiết kế','15/04/2004','16/08/2021')

	